[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Uncomment to use this redirect for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to set cache-control and security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data:; media-src 'self' https:; connect-src 'self' https:; font-src 'self' https: data:;"
    Cache-Control = "public, max-age=31536000"

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Production context
[context.production]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "production" }

# Deploy preview context
[context.deploy-preview]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "production" }

# Branch deploy context
[context.branch-deploy]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "production" }

# Development server settings
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  publish = "dist"
  framework = "#custom"
  autoLaunch = true 